name: GKTYW
favicon: null
layout_spectrum: 0.7382079239469022
typography_spectrum: 0.369700524257496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5501288722734898
  lightness: 0.5394345845561475
  saturation: 0.13422766351141036
  rhythmicContrast: 0.6850267944391817
purpose: []
